### ISSUE TITLE
The 'Recent Updates' heading is unnecessary

### ISSUE THREAD

**Issue by hlashbrooke** [woocommerce/houston#10]
The 'Recent Updates' heading above the posts feels unnecessary. IMO, it should be removed and the two buttons that it contains should be floated above the post list.

**Comment by jameskoster** [comment]
I'd rather leave this as is for a couple of reasons;
- The only way to remove it is to overwrite the entire index.php file which I'd rather avoid
- It balances nicely with the 'whatcha up to' heading
- It is useful when paging through posts and I prefer the consistency of it being there on all pages rather than not there on the homepage, but visible on all others
- If it's removed, the icons still need to be there so it wouldn't really save any space
