### ISSUE TITLE
Minimize post box

### ISSUE THREAD

**Issue by mjepson** [woocommerce/houston#16]
The post box takes up much real estate on the screen, so it would be cool if it could be minimized somehow when not using it. Maybe only show the first "Hi, Magnus. Whatcha up to?" box, and when you click on that it pops the whole box open?

http://d.pr/i/HwHY/1AvrSHGq

**Comment by hlashbrooke** [comment]
For ease of use, it would be nice if this was open by default, so you have the option of closing it. I like having it open all the time because now I have one extra action to perform before I get to post anything. The minimise option is cool, but should be open by default I think. Or possibly remember what the user last had and when the page loads make it open or closed based on that.

**Comment by jameskoster** [comment]
Thoughts @mjepson ? Worth making it open by default then using a cookie to remember your selection?

**Comment by mjepson** [comment]
Not worth it imo.

**Comment by hlashbrooke** [comment]
Then perhaps make it so that when you expand the post box, it places the cursor in the textarea. A simple `.focus()` should do it - will save one extra click when trying to post :)
